plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
    id 'idea'
}

version = '1.0.14'
group = 'igentuman.blockbooster'
archivesBaseName = 'BlockBooster-1.20.1'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
minecraft {

    mappings channel: 'parchment', version: "2023.09.03-1.20.1"
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.disableRefMap', 'true'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                blockbooster {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.disableRefMap', 'true'
            mods {
                blockbooster {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.disableRefMap', 'true'
            args '--mod', 'blockbooster', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/'),
            mods {
                blockbooster {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { // JEI
        url "https://dvs1.progwml6.com/files/maven"
    }
    maven { // TOP
        url "https://cursemaven.com"
    }
    maven { url 'https://maven.blamejared.com' }
    maven {
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name 'Modmaven'
        url 'https://modmaven.dev/'
        content {
            includeGroup 'mekanism'
        }
    }
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven { url "https://maven.architectury.dev" }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.6'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation 'org.spongepowered:mixin:0.8.5'
    runtimeOnly fg.deobf("curse.maven:nbtedit-reborn-678133:5984630")
    implementation fg.deobf("mekanism:Mekanism:${mekanism_version}")
    compileOnly fg.deobf("vazkii.botania:Botania:${botania_version}:api")
    compileOnly fg.deobf("vazkii.botania:Botania:${botania_version}")
    compileOnly fg.deobf("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${mc_version}-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}")
    //runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}")
    //compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}:api")
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:${patchouli_version}:api")
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:${patchouli_version}")
    implementation fg.deobf("curse.maven:masterful-machinery-423476:5818581")
    //runtimeOnly fg.deobf("curse.maven:the-one-probe-245211:3550084")
    implementation fg.deobf("dev.architectury:architectury-forge:${architectury_version}")
    implementation fg.deobf("dev.latvian.mods:kubejs-forge:${kubejs_version}"){
        transitive = false
    }

    implementation fg.deobf("dev.latvian.mods:rhino-forge:${rhino_version}"){
        transitive = false
    }
}

mixin {
    add sourceSets.main, "blockbooster.refmap.json"
    config "blockbooster.mixins.json"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "blockbooster",
                "Specification-Vendor"    : "igentuman",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "igentuman",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

configurations {
    shaded {
        transitive = false
    }
}

shadowJar {
    dependsOn jar
    finalizedBy 'reobfShadowJar'

    from sourceSets.main.output.classesDirs
    from sourceSets.main.output.resourcesDir

    manifest {
        attributes([
                "Specification-Title"   : "blockbooster",
                "Specification-Vendor"  : "igentuman",
                "Specification-Version" : "${project.version}",
                "Implementation-Title"  : "${project.name}",
                "Implementation-Version": "${version}",
                "Implementation-Vendor" : "igentuman",
                "MixinConfigs"          : "blockbooster.mixins.json"
        ])
    }

    configurations = [project.configurations.shaded]
    archiveClassifier = null
}



reobf {
    shadowJar {}
}

afterEvaluate {
    tasks.reobfJar.enabled = false
}

tasks.assemble.dependsOn reobfShadowJar