# Update memory settings if needed
org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=/home/igentuman/.jdks/liberica-full-25.0.3
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Update Minecraft and NeoForge versions
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84

# Define mod properties
mod_id=blockbooster
mod_name=Block Booster
mod_license=MIT
mod_version=1.1.13
mod_group_id=igentuman.blockbooster
mod_authors=igentuman
mod_description=Increase tick rate of blocks. Requires energy or mana

# Update dependency versions for 1.21
# You'll need to find compatible versions for each dependency
jei_version=29.16.0.48

#mekanism_version=1.21.1-10.7.16.82
#botania_version=1.21.10-xxx-NEOFORGE
#patchouli_version=1.21.10-xx-NEOFORGE
