modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="blockbooster" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Block Booster" #mandatory
logoFile="logo.png" #optional
credits="Boosting machines with energy" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Increase tick rate for machines on top of block booster. Requires energy
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.blockbooster]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.blockbooster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
